/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import control.RegistroDeLaborCulturalControl;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.RegistroDeLaborCultural;

/**
 *
 * @author JohnFredy
 */
public class CRUDRegistroDeLaborCulturalGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegistroDeLaborCulturalView
     */
    private boolean editing = false;
    private int filaEditable = -1;
    private ArrayList registroDeLaboresCulturales = new ArrayList();
    
    public CRUDRegistroDeLaborCulturalGUI() {
        initComponents();
        cargarTabla();
        registroDeLaborCulturalTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int fila = registroDeLaborCulturalTable.rowAtPoint(e.getPoint());
                int columna = registroDeLaborCulturalTable.columnAtPoint(e.getPoint());
                if (editing && fila > -1 && columna > -1) {
                    if (filaEditable != -1 && fila == filaEditable) {
                        String mensaje = "";
                        switch (columna) {
                            case 0:
                                mensaje = "Ingrese la fecha así: dd/mm/aaaa";
                                break;
                            case 1:
                                mensaje = "Ingrese la labor realizada";
                                break;
                            case 2:
                                mensaje = "Ingrese el(a) fresicultor(a)";
                                break;
                            case 3:
                                mensaje = "Ingrese el No. de jornales";
                                break;
                            case 4:
                                mensaje = "Ingrese las observaciones ";
                                break;
                        }
                        String m = JOptionPane.showInputDialog(mensaje);
                        registroDeLaborCulturalTable.setValueAt(m, fila, columna);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        registroDeLaborCulturalTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        agregarButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registroDeLaborCulturalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Labor Realizada", "Fresicultor", "No. Jornales", "Observaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(registroDeLaborCulturalTable);
        if (registroDeLaborCulturalTable.getColumnModel().getColumnCount() > 0) {
            registroDeLaborCulturalTable.getColumnModel().getColumn(0).setResizable(false);
            registroDeLaborCulturalTable.getColumnModel().getColumn(1).setResizable(false);
            registroDeLaborCulturalTable.getColumnModel().getColumn(2).setResizable(false);
            registroDeLaborCulturalTable.getColumnModel().getColumn(3).setResizable(false);
            registroDeLaborCulturalTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Registro de Labores Culturales");

        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        borrarButton.setText("Borrar");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agregarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guardarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(agregarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guardarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(borrarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        // TODO add your handling code here:
        if (!editing) {
            DefaultTableModel modelo = (DefaultTableModel) registroDeLaborCulturalTable.getModel();
            modelo.addRow(new Object[5]);
            filaEditable = modelo.getRowCount() - 1;
            guardarButton.setEnabled(true);
            editing = true;
        }
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        // TODO add your handling code here:
        if (registroDeLaborCulturalTable.getSelectedRow() > -1) {
            RegistroDeLaborCultural rc = (RegistroDeLaborCultural) registroDeLaboresCulturales.get(registroDeLaborCulturalTable.getSelectedRow());
            new RegistroDeLaborCulturalControl().eliminar(rc);
            borrarTabla();
            cargarTabla();
        }
        guardarButton.setEnabled(false);
        editing = false;
        RegistroDeLaborCultural rc = new RegistroDeLaborCultural();
        try {
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
            String strFecha = (String) registroDeLaborCulturalTable.getValueAt(filaEditable, 0);
            strFecha = strFecha.replaceAll(" ", "");
            Date fecha = null;
            fecha = formatoDelTexto.parse(strFecha);
            rc.setFecha(fecha);
            rc.setLaborCultural(null); // Toca ver la forma de que puedan entrar
            rc.setFresicultor(null);    // Toca ver la forma de que puedan entrar
            rc.setJornales(Double.parseDouble((String) registroDeLaborCulturalTable.getValueAt(filaEditable, 3)));
            rc.setObservaciones((String) registroDeLaborCulturalTable.getValueAt(filaEditable, 4));
            if (!new RegistroDeLaborCulturalControl().crear(rc)) {
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        borrarTabla();
        cargarTabla();
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDRegistroDeLaborCulturalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDRegistroDeLaborCulturalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDRegistroDeLaborCulturalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDRegistroDeLaborCulturalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDRegistroDeLaborCulturalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton borrarButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable registroDeLaborCulturalTable;
    // End of variables declaration//GEN-END:variables
    
    private void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) registroDeLaborCulturalTable.getModel();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        registroDeLaboresCulturales = (ArrayList) new RegistroDeLaborCulturalControl().leerTodos();
        for (int i = 0; i < registroDeLaboresCulturales.size(); i++) {
            RegistroDeLaborCultural rc = (RegistroDeLaborCultural) registroDeLaboresCulturales.get(i);
            String fecha = sdf.format(rc.getFecha());
            String[] datos = {fecha, rc.getLaborCultural().getNombre(),
                rc.getFresicultor().getApellidos(),Double.toString(rc.getJornales()),rc.getObservaciones()};
            modelo.addRow(datos);
        }
    }

    private void borrarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) registroDeLaborCulturalTable.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
}
